status=info
name=Log4j2PropertiesConfig
appenders=console
appender.console.type=Console
appender.console.name=LogToConsole
appender.console.layout.type=PatternLayout
appender.console.layout.pattern=%highlight{%d{yyyy-MM-dd HH:mm:ss.SSS}{GMT-3} %-4level: %m%n%throwable}
rootLogger.level=info
rootLogger.appenderRefs=stdout
rootLogger.appenderRef.stdout.ref=LogToConsole